const CartActionTypes = {
    SHOW_HIDE_CART: 'SHOW_HIDE_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    EMPTY_CART: 'EMPTY_CART'
}

export default CartActionTypes;